#include 'totvs.ch'
#include 'fwmvcdef.ch'

#include 'tlpp-core.th'

namespace custom.app.agenda.api.cadastros

/*/{Protheus.doc} U_GET
    Funcao para consulta de dados cadastrais
    @type  Function
    @author Klaus Wolfgram
    @since 14/04/2026
    @version 1.0

    https://erp:2200/api/custom/app/agenda/cadastros/atendentes
    /*/

    @get(endpoint="custom/app/agenda/cadastros/:recurso",description="API para consulta de dados cadastrais.")
Function U_GET() as Logical

    Local err       as Object
    Local cMsgErr   as Character

    Local cBody     as Character
    Local jBody     as Json
    Local jHeader   as Json
    Local jPath     as Json
    Local jQuery    as Json

    Local jResp     as Json

    Local cRecurso  as Character
    Local xRecno    as Variant
    Local xData     as Variant

    try

        err     := errorClass():new()
        cMsgErr := ''
        
        cBody   := oRest:getBodyRequest()
        jBody   := jsonObject():new()
        jBody:fromJson(cBody)

        jHeader := oRest:getHeaderRequest()
        jQuery  := oRest:getQueryRequest()
        jPath   := oRest:getPathParamsRequest()

        cRecurso:= upper(jPath['recurso'])
        xRecno  := jHeader['recno']

        IF valtype(xRecno) == 'U'
            xRecno := 0
        ElseIF valtype(xRecno) == 'C'
            xRecno := val(xRecno)
        ElseIF valtype(xRecno) == 'N'
            xRecno := xRecno
        Else
            xRecno := 0
        EndIF

        DO CASE 
            CASE cRecurso == 'ATENDENTES'
                xData := fnGetAtendentes(xRecno,jQuery)

            OTHERWISE
                err:description := 'RECURSO INVALIDO -> ' + cRecurso
                throw err

        END CASE

        jResp           := jsonObject():new()
        jResp['status' ]:= 'success'
        jResp['recurso']:= cRecurso
        jResp['message']:= ''
        jResp['data'   ]:= xData

        oRest:setResponse(jResp:toJson())

    catch e

        IF !empty(e:description)
            
            cMsgErr := alltrim(e:description)

            IF !empty(e:errorstack)
                cMsgErr += CRLF + "ERRORSTACK -->> " + LEFT(e:errorstack,500)
            EndIF

        EndIF

        jResp           := jsonObject():new()
        jResp['status' ]:= 'error'
        jResp['recurso']:= cRecurso
        jResp['message']:= cMsgErr 
        jResp['data'   ]:= {}

        oRest:setFault(jResp:toJson())        

    endtry
    
Return .T.

    @post(endpoint="custom/app/agenda/cadastros/:recurso",description="API para inclusao de registros")
Function U_POST()

    Local err       as Object
    Local cMsgErr   as Character

    Local cBody     as Character
    Local jBody     as Json
    Local jHeader   as Json
    Local jQuery    as Json
    Local jPath     as Json

    Local jResp     as Json

    Local cRecurso  as Character

    Local cNome     as Character
    Local cFuncao   as Character
    Local cEmail    as Character

    Local aCampos   as Array
    Local x         as Numeric

    Local nRecno    as Numeric
    Local cCodigo   as Character

    try

        err         := errorClass():new()      

        cBody       := oRest:getBodyRequest()
        jBody       := jsonObject():new()
        jBody:fromJson(cBody)

        jHeader     := oRest:getHeaderRequest()
        jQuery      := oRest:getQueryRequest()
        jPath       := oRest:getPathParamsRequest()

        cRecurso    := upper(jPath['recurso'])

        DO CASE
            
            CASE cRecurso == 'ATENDENTES'
                
                cNome   := jBody['nome'  ]
                cFuncao := jBody['funcao']
                cEmail  := jBody['email' ]

                aCampos := fwSx3Util():getAllFields('AA1',.F.)

                AA1->(dbSetOrder(1),reclock("AA1",.T.))

                    For x := 1 To Len(aCampos)
                        AA1->&(aCampos[x]) := criavar(aCampos[x],.T.)
                    Next

                    AA1->AA1_FILIAL := xFilial("AA1")
                    AA1->AA1_NOMTEC := cNome
                    AA1->AA1_FUNCAO := cFuncao
                    AA1->AA1_EMAIL  := cEmail

                AA1->(msunlock())

                IF __LSX8
                    confirmSX8()
                EndIF

                cCodigo     := AA1->AA1_CODTEC
                nRecno      := AA1->(recno())

                jAtendente            := jsonObject():new()
                jAtendente['id'     ] := nRecno
                jAtendente['codigo' ] := cCodigo
                jAtendente['nome'   ] := cNome

                jResp               := jsonObject():new()
                jResp['status' ]    := 'success'
                jResp['message']    := 'Novo atendente incluido com sucesso.'
                jResp['data'   ]    := jAtendente
                jResp['recurso']    := cRecurso

                oRest:setResponse(jResp:toJson())

            OTHERWISE
                
                err:description := 'Recurso invalido: ' + cRecurso
                throw err

        END CASE 

    catch e

        IF !empty(e:description)
            
            cMsgErr := alltrim(e:description)

            IF !empty(e:errorstack)
                cMsgErr += CRLF + "ERRORSTACK -->> " + LEFT(e:errorstack,500)
            EndIF

        EndIF

        jResp           := jsonObject():new()
        jResp['status' ]:= 'error'
        jResp['recurso']:= cRecurso
        jResp['message']:= cMsgErr 
        jResp['data'   ]:= ''

        oRest:setFault(jResp:toJson())        

    endtry    
    
Return .T.

    @put(endpoint="custom/app/agenda/cadastros/:recurso/:id",description="API para inclusao de registros")
Function U_PUT()
    
    Local err       as Object
    Local cMsgErr   as Character

    Local cBody     as Character
    Local jBody     as Json
    Local jHeader   as Json
    Local jQuery    as Json
    Local jPath     as Json

    Local jResp     as Json

    Local cRecurso  as Character
    Local nRecno    as Numeric

    Local cNome     as Character
    Local cFuncao   as Character
    Local cEmail    as Character

    Local aCampos   as Array
    Local x         as Numeric

    try

        err         := errorClass():new()      

        cBody       := oRest:getBodyRequest()
        jBody       := jsonObject():new()
        jBody:fromJson(cBody)

        jHeader     := oRest:getHeaderRequest()
        jQuery      := oRest:getQueryRequest()
        jPath       := oRest:getPathParamsRequest()

        cRecurso    := upper(jPath['recurso'])
        nRecno      := val(jPath['id'])

        DO CASE
            
            CASE cRecurso == 'ATENDENTES'

                AA1->(dbSetOrder(1),dbGoTo(nRecno))

                IF AA1->(eof())
                    err:description := 'ID invalido'
                    throw err
                EndIF
                
                cNome   := jBody['nome'  ]
                cFuncao := jBody['funcao']
                cEmail  := jBody['email' ]

                aCampos := fwSx3Util():getAllFields('AA1',.F.)

                AA1->(dbSetOrder(1),reclock("AA1",.F.))

                    AA1->AA1_FILIAL := xFilial("AA1")
                    AA1->AA1_NOMTEC := cNome
                    AA1->AA1_FUNCAO := cFuncao
                    AA1->AA1_EMAIL  := cEmail

                AA1->(msunlock())

                jAtendente            := jsonObject():new()

                For x := 1 To Len(aCampos)
                    cCampo              := alltrim(aCampos[x])
                    cTitulo             := strtran(strtran(alltrim(getSX3Cache(cCampo,'X3_TITULO'))," ","-"),".","")
                    xConteudo           := AA1->&(cCampo)
                    jAtendente[cTitulo] := xConteudo
                Next

                jResp               := jsonObject():new()
                jResp['status' ]    := 'success'
                jResp['message']    := 'Cadastro atualizado com sucesso!'
                jResp['data'   ]    := jAtendente
                jResp['recurso']    := cRecurso

                oRest:setResponse(jResp:toJson())

            OTHERWISE
                
                err:description := 'Recurso invalido: ' + cRecurso
                throw err

        END CASE 

    catch e

        IF !empty(e:description)
            
            cMsgErr := alltrim(e:description)

            IF !empty(e:errorstack)
                cMsgErr += CRLF + "ERRORSTACK -->> " + LEFT(e:errorstack,500)
            EndIF

        EndIF

        jResp           := jsonObject():new()
        jResp['status' ]:= 'error'
        jResp['recurso']:= cRecurso
        jResp['message']:= cMsgErr 
        jResp['data'   ]:= ''

        oRest:setFault(jResp:toJson())        

    endtry

Return .T.

    @delete("custom/app/agenda/cadastros/:recurso/:id")
Function U_DELETE()
    
    Local err       as Object
    Local cMsgErr   as Character

    Local cBody     as Character
    Local jBody     as Json
    Local jHeader   as Json
    Local jQuery    as Json
    Local jPath     as Json

    Local jResp     as Json

    Local cRecurso  as Character
    Local nRecno    as Numeric

    try

        err         := errorClass():new()      

        cBody       := oRest:getBodyRequest()
        jBody       := jsonObject():new()
        jBody:fromJson(cBody)

        jHeader     := oRest:getHeaderRequest()
        jQuery      := oRest:getQueryRequest()
        jPath       := oRest:getPathParamsRequest()

        cRecurso    := upper(jPath['recurso'])
        nRecno      := val(jPath['id'])

        DO CASE
            
            CASE cRecurso == 'ATENDENTES'

                AA1->(dbSetOrder(1),dbGoTo(nRecno))

                IF AA1->(eof())
                    err:description := 'Recurso/Registro nao encontrados!'
                    throw err
                EndIF

                AA1->(reclock("AA1",.F.), dbDelete(), msunlock())

                jResp               := jsonObject():new()
                jResp['status' ]    := 'success'
                jResp['message']    := 'Registro ID: ' + jPath['id'] + ' excluido com sucesso!'
                jResp['data'   ]    := ''
                jResp['recurso']    := cRecurso

                oRest:setResponse(jResp:toJson())

            OTHERWISE
                
                err:description := 'Recurso invalido: ' + cRecurso
                throw err

        END CASE 

    catch e

        IF !empty(e:description)
            
            cMsgErr := alltrim(e:description)

            IF !empty(e:errorstack)
                cMsgErr += CRLF + "ERRORSTACK -->> " + LEFT(e:errorstack,500)
            EndIF

        EndIF

        jResp           := jsonObject():new()
        jResp['status' ]:= 'error'
        jResp['recurso']:= cRecurso
        jResp['message']:= cMsgErr 
        jResp['data'   ]:= ''

        oRest:setFault(jResp:toJson())        

    endtry

Return .T.

Static Function fnGetAtendentes(xRecno as Numeric,JQuery as Json) as Variant

    Local xData      as Variant
    Local jAtendente as Json
    Local aCampos    as Array
    Local x          as Numeric

    IF xRecno > 0

        AA1->(dbSetOrder(1),dbGoTo(xRecno))
        aCampos     := fwSx3Util():getAllFields('AA1',.F.)

        xData       := jsonObject():new()

        For x := 1 To Len(aCampos)

            cCampo  := alltrim(aCampos[x])
            xCampo  := strtran(alltrim(getSx3Cache(cCampo,"X3_TITULO"))," ","-")
            xData[xCampo] := AA1->(&(cCampo))

        Next

    Else
        
        xData := array(0)

        AA1->(dbSetOrder(1),dbSeek(xFilial("AA1")))

        While !AA1->(eof()) .and. AA1->AA1_FILIAL == xFilial("AA1")

            IF !empty(jQuery['funcao'])
                IF AA1->AA1_FUNCAO <> jQuery['funcao']
                    AA1->(dbSkip())
                    Loop
                EndIF
            EndIF

            IF !empty(jQuery['nome'])
                IF !(alltrim(upper(jQuery['nome'])) $ AA1->AA1_NOMTEC)
                    AA1->(dbSkip())
                    Loop
                EndIF
            EndIF

            jAtendente           := jsonObject():new()
            jAtendente['recno' ] := AA1->(recno())
            jAtendente['filial'] := AA1->AA1_FILIAL
            jAtendente['codigo'] := AA1->(alltrim(AA1_CODTEC))
            jAtendente['nome'  ] := AA1->(alltrim(AA1_NOMTEC))

            aadd(xData,jAtendente)

            AA1->(dbSkip())

        Enddo

    EndIF
    
Return xData
