#include 'totvs.ch'
#include 'tlpp-core.th'

namespace custom.app.agenda.fila.integracao

/*/{Protheus.doc} U_PROCESSA
    Programa para processamento dos registros da tabela de integracao do app agenda do tecnico.
    @type  Function
    @author Klaus Wolfgram
    @since 07/06/2026
    @version 1.0

    custom.app.agenda.fila.integracao.U_PROCESSA
    /*/
Function U_PROCESSA()   as Logical

    Local lret          as Logical
    Local lRPC          as Logical

    Local bLastError    as Codeblock
    Local cMsgErr       as Character
    Local aRecSZ1       as Array
    Local x             as Numeric

    Private err         as Object

    bLastError          := errorBlock({|e| err := e, break(e)})

    IF type('cEmpAnt') <> 'C'
        rpcSetEnv('99','01')
        lRPC            := .T.
    EndIF

    BEGIN SEQUENCE

        aRecSZ1         := fnGetSZ1()

        For x := 1 To Len(aRecSZ1)

            SZ1->(dbSetOrder(1),dbGoTo(aRecSZ1[x]))

            IF SZ1->(alltrim(Z1_ORIGEM)) == 'ATENDIMENTO'
                fnProcAtend()
            ElseIF SZ1->(alltrim(Z1_ORIGEM)) $ 'GALERIA|ASSINATURA'
                fnProcImagem()
            EndIF

        Next

    RECOVER
        
        IF !empty(err:description)
            cMsgErr := alltrim(err:description)

            IF !(err:errorstack)
                cMsgErr += CRLF + LEFT(err:errorstack,400)
            EndIF
        EndIF

        conout("custom.app.agenda.fila.integracao.U_PROCESSA" + cMsgErr)

    END SEQUENCE

    errorBlock(bLastError)

    IF lRPC
        rpcClearEnv()
    EndIF
    
Return lret

/*/{Protheus.doc} fnProcAtend
    Processa os atendimentos.
    @type  Static Function
    @author Klaus Wolfgram
    @since 08/06/2026
    /*/
Static Function fnProcAtend()

    Local aCab          as Array
    Local jBody         as Json
    Local nIndAAG       as Numeric

    Local cChaveAAG     as Character

    Local dDataChegada  as Date
    Local dDataInicio   as Date
    Local dDataFim      as Date

    Local cHoraChegada  as Character
    Local cHoraInicio   as Character
    Local cHoraFim      as Character
    Local cTraslado     as Character
    Local cStatus       as Character
    Local cSequencia    as Character
    Local cTexto        as Character

    Local nOpc          as Numeric
//  Local lAchou        as Logical

    Private lMsErroAuto as Logical

    aCab                := array(0)
    
    jBody               := jsonObject():new()
    jBody:fromJson(decodeUTF8(SZ1->Z1_DADOS))

    nIndAAG             := AAG->(retOrder('AAG','AAG_FILIAL+AAG_DESCRI'))

    cChaveAAG           := xFilial("AAG")+PADR(jBody['ocorrencia'],tamSX3('AAG_DESCRI')[1])
    cCodTec             := jBody['tecnico']

    IF empty(cCodTec)
        SZ1->(reclock("SZ1",.F.), Z1_STATUS := '2', Z1_MSGPROC := 'Tecnico não informado!')
        return
    EndIF

    IF !AA1->(dbSetOrder(1),dbSeek(xFilial(alias())+cCodTec))
        SZ1->(reclock("SZ1",.F.), Z1_STATUS := '2', Z1_MSGPROC := 'Tecnico não encontrado!' + CRLF + jBody['tecnico'])
        return
    EndIF

    SZ1->(reclock(alias(),.F.), Z1_CODTEC := AA1->AA1_CODTEC, SZ1->Z1_NOMTEC := AA1->AA1_NOMTEC, msunlock())

    IF !AAG->(dbSetOrder(1),dbSeek(xFilial(alias())+jBody['ocorrencia']))
        IF !AAG->(dbSetOrder(nIndAAG),dbSeek(cChaveAAG))
            SZ1->(reclock("SZ1",.F.), Z1_STATUS := '2', Z1_MSGPROC := 'Ocorrência não encontrada!' + CRLF + jBody['ocorrencia'])
            return
        EndIF
    EndIF

    nRecAB7             := if(valtype(jBody['id_os']) == 'C',val(jBody['id_os']),jBody['id_os']);

    AB7->(dbSetOrder(1),dbGoTo(nRecAB7))

    dDataChegada        := CTOD(LEFT(jBody['chegada'],10))
    dDataInicio         := CTOD(LEFT(jBody['inicio' ],10))
    dDataFim            := CTOD(LEFT(jBody['fim'    ],10))

    cHoraChegada        := STRTRAN(RIGHT(jBody['chegada'],5),":","")
    cHoraInicio         := STRTRAN(RIGHT(jBody['inicio' ],5),":","")
    cHoraFim            := STRTRAN(RIGHT(jBody['fim'    ],5),":","")
    cTraslado           := STRTRAN(jBody['traslado'     ],":","")
    
    cTraslado           := if('undefined' $ cTraslado .or. empty(cTraslado),'0000',cTraslado)
    cStatus             := IF(upper(jBody['situacao']) == 'ENCERRADO','1','2')
    cTexto              := jBody['texto']

    //-- chave para garantir idempotencia na gravacao do atendimento
    cIdApp              := SZ1->Z1_IDAPP

    //-- se nao existir ou estiver sem conteudo, encerra a execuccao
    IF empty(cIdApp)
        SZ1->(reclock("SZ1",.F.), Z1_STATUS := '2', Z1_MSGPROC := 'Id do App nao informado.')
        return
    EndIF

    //-- Normaliza o id de acordo com o tamanho do campo para correta execucao da busca por indice
    cIdApp              := padr(cIdApp,tamSX3('AB9_YID')[1])

    //-- Verifica se o registro ja existe
    IF AB9->(dbOrderNickName('IDAPP'),dbSeek(xFilial(alias())+cIdApp))
        SZ1->(reclock("SZ1",.F.), Z1_STATUS := '1', Z1_RECNO := AB9->(recno()), Z1_MSGPROC := 'Atendimento registrado anteriormente.')
        return
    EndIF

    //-- Recno sendo enviado como texto e como numerico
    nRecAB9             := if(valtype(jBody['id']) == 'C' .and. !empty(jBody['id']),val(jBody['id']),jBody['id'])
    
    //-- Verifica se o registro existe baseado no recno, nesse caso nao registra novamente.
    IF !empty(nRecAB9)
        
        //-- AB9->(dbSetOrder(1),dbGoTo(jBody['id']))
        //-- cSequencia      := AB9->AB9_SEQ
        //-- nOpc            := 4

        SZ1->(reclock("SZ1",.F.), Z1_STATUS := '1', Z1_RECNO := nRecAB9, Z1_MSGPROC := 'Atendimento registrado anteriormente.')
        return
    
    EndIF

    AB9->(dbSetOrder(1),dbSeek(AB7->(AB7_FILIAL+AB7_NUMOS+AB7_ITEM)))
    
    cSequencia      := '01'
    nOpc            := 3
        
    While !AB9->(eof()) .and. AB9->(AB9_FILIAL+AB9_NUMOS) == AB7->(AB7_FILIAL+AB7_NUMOS+AB7_ITEM)
            
        //-- cSequencia := AB9->AB9_SEQ
        //-- IF AB9->AB9_CODTEC == AA1->AA1_CODTEC .and. AB9->AB9_DTINI == dDataInicio .and. AB9->AB9_HRINI == cHoraInicio
        //--     lAchou      := .T.
        //--     nOpc        := 4
        //--     cSequencia  := AB9->AB9_SEQ
        //--     Exit
        //-- EndIF

        cSequencia  := soma1(cSequencia)
        AB9->(dbSkip())

    Enddo

    /*/
    IF !lAchou
        cSequencia  := soma1(cSequencia)
        nOpc        := 3
    EndIF
    /*/

    aadd(aCab,{"AB9_NUMOS"  ,AB7->(AB7_NUMOS+AB7_ITEM)  ,})
    aadd(aCab,{"AB9_SEQ"    ,cSequencia                 ,})    
    aadd(aCab,{"AB9_CODTEC" ,AA1->AA1_CODTEC            ,})
    aadd(aCab,{"AB9_DTCHEG" ,dDataChegada               ,})
    aadd(aCab,{"AB9_HRCHEG" ,cHoraChegada               ,})
    aadd(aCab,{"AB9_DTSAID" ,dDataFim                   ,})
    aadd(aCab,{"AB9_HRSAID" ,cHoraFim                   ,})
    aadd(aCab,{"AB9_DTINI"  ,dDataInicio                ,})
    aadd(aCab,{"AB9_HRINI"  ,cHoraInicio                ,})
    aadd(aCab,{"AB9_DTFIM"  ,dDataFim                   ,})
    aadd(aCab,{"AB9_HRFIM"  ,cHoraFim                   ,})
    aadd(aCab,{"AB9_TRASLA" ,cTraslado                  ,})
    aadd(aCab,{"AB9_CODPRB" ,AAG->AAG_CODPRB            ,})
    aadd(aCab,{"AB9_TIPO"   ,cStatus                    ,})
    aadd(aCab,{"AB9_MEMO2"  ,cTexto                     ,})
    aadd(aCab,{"AB9_YID"    ,cIdApp                     ,})

    lMsErroAuto := .F.

    msExecAuto({|x,y,z| teca460(x,y,z)},aCab,array(0),nOpc)

    IF lMsErroAuto
        
        mostraerro('\data\','erro.txt')
        
        cMsgErr := memoread('\data\erro.txt')
        SZ1->(reclock(alias(),.F.), Z1_STATUS := '2', Z1_MSGPROC := cMsgErr         ,msunlock())

    Else

        SZ1->(reclock(alias(),.f.), Z1_STATUS := '1', Z1_RECNO   := AB9->(recno())  ,msunlock())
        
    EndIF
        
Return 

/*/{Protheus.doc} fnProcImagem
    Programa para processamento das imagens
    @type  Static Function
    @author Klaus Wolfgram
    @since 08/06/2026
    /*/
Static Function fnProcImagem()
    
Return 

/*/{Protheus.doc} fnGetSZ1
    Lista os registros pendentes de processamento.
    @type  Static Function
/*/
Static Function fnGetSZ1() as array

    Local aRecSZ1   as Array
    Local cSQL      as Character
    Local cAliasSQL as Character

    aRecSZ1         := array(0)

    cSQL            := "SELECT R_E_C_N_O_ RECSZ1"
    cSQL            += CRLF + "FROM " + RETSQLNAME("SZ1") + " SZ1"
    cSQL            += CRLF + "WHERE SZ1.D_E_L_E_T_ = ' ' "
    cSQL            += CRLF + "AND Z1_RECNO = 0"
    cSQL            += CRLF + "AND Z1_STATUS = ' ' "
    cSQL            += CRLF + "ORDER BY R_E_C_N_O_"

    cAliasSQL       := mpSysOpenQuery(cSQL)

    (cAliasSQL)->(dbEval({|| aadd(aRecSZ1,RECSZ1)}),dbCloseArea())
    
Return aRecSZ1
