#include 'totvs.ch'
#include 'fwmvcdef.ch'
#include 'tlpp-core.th'

namespace custom.app.agenda.mvc

/*/{Protheus.doc} U_BROWSE
    (long_description)
    @type  Function
    @author user
    @since 11/04/2026
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
    /*/
Function U_BROWSE() 

    Local aRotina as Array
    Local xVar as Variant

    Local cVar as Character
    Local nVar as Numeric
    Local lVar as Logical
    Local dVar as Date

    xVar := 0
    
Return 

/*/{Protheus.doc} U_MENUDEF
    (long_description)
    @type  Function
    @author user
    @since 11/04/2026
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
    /*/
Function U_MENUDEF(lResumido as Logical) as Array

    Local aRotina := {}

    add option aRotina title 'Incluir' action 'viewdef.custom.app.agenda.mvc.browse' operation 3 access 0 
    
Return aRotina

/*/{Protheus.doc} U_VIEWDEF
    (long_description)
    @type  Function
    @author user
    @since 11/04/2026
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
    /*/
Function U_VIEWDEF()

    Local oModel := fwLoadModel('custom.app.agenda.mvc.browse')
    
Return oView

/*/{Protheus.doc} U_MODELDEF
    (long_description)
    @type  Function
    @author user
    @since 11/04/2026
    @version version
    @param param_name, param_type, param_descr
    @return return_var, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
    /*/
Function U_MODELDEF()
    
Return oModel
