#include 'totvs.ch'
#include 'tlpp-core.th'

namespace custom.app.agenda.api.tabelas

/*/{Protheus.doc} U_GET
    Programa para listagem de tabelas auxiliares do ERP
    @type  Function
    @author Klaus Wolfgram
    @since 15/05/2026
    @version 1.0
    /*/

    @get(endpoint="custom/app/agenda/tabelas/:recurso",description="API para consulta de dados de tabelas auxiliares.")
Function U_GET() as Logical

    Local err       as Object
    Local cMsgErr   as Character

    Local jHeader   as Json
    Local jPath     as Json
    Local jQuery    as Json

    Local cRecurso  as Character
    Local xData     as Variant

    Local jResp     as Json

    try

        err         := errorClass():new()
        cMsgErr     := ''

        jHeader     := oRest:getHeaderRequest()
        jQuery      := oRest:getQueryRequest()
        jPath       := oRest:getPathParamsRequest()

        cRecurso    := jPath['recurso']

        DO CASE
            CASE cRecurso == 'servicos'
                xData := fnGetData('AA5','AA5_FILIAL','AA5_CODSER','AA5_DESCRI')
            CASE cRecurso == 'ocorrencias'
                xData := fnGetData('AAG','AAG_FILIAL','AAG_CODPRB','AAG_DESCRI')

            OTHERWISE
                err:description := 'RECURSO INVALIDO: ' + cRecurso
                throw err

        ENDCASE

        jResp            := jsonObject():new()
        jResp['status' ] := 'success'
        jresp['recurso'] := cRecurso
        jResp['message'] := ''
        jResp['data'   ] := xData 

        oRest:setResponse(jResp:toJson())

    catch e

        IF !empty(e:description)
            cMsgErr := alltrim(e:description)

            IF !empty(e:errorstack)
                cMsgErr += CRLF + LEFT(e:errorstack,500)
            EndIF
        EndIF

        jResp            := jsonObject():new()
        jResp['status' ] := 'error'
        jresp['recurso'] := cRecurso
        jResp['message'] := cMsgErr        
        jResp['data'   ] := nil

        oRest:setFault(jResp:toJson())

    finally

    endtry

    
Return .T.

/*/{Protheus.doc} fnGetData
    Funcao auxiliar para recuperacao dos registros retornados pela API.
    @type  Static Function
    @author Klaus Wolfgram
    @since 15/05/2026
    @version 1.0
/*/
Static Function fnGetData(cTabela,cCampoFilial,cCampoCodigo,cCampoDescri)

    Local cCodigo       as Character
    Local cDescricao    as Character

    Local xData         as Variant
    Local jLinha        as Json

    //-- AAG->(dbSetOrder(1),dbSeek(xFilial('AAG')))
    //-- While !AAG->(eof()) .and. AAG->AAG_FILIAL == xFilial("AAG")

    (cTabela)->(dbSetOrder(1),dbSeek(xFilial(cTabela)))

    xData               := array(0)

    While !(cTabela)->(eof()) .and. (cTabela)->(&(cCampoFilial)) == xFilial(cTabela)

        cCodigo         := (cTabela)->(&(cCampoCodigo))
        cDescricao      := (cTabela)->(&(cCampoDescri))

        jLinha          := jsonObject():new()
        jLinha['id']    := (cTabela)->(recno())
        jLinha['filial']:= alltrim((cTabela)->(&(cCampoFilial)))
        jLinha['codigo']:= alltrim((cTabela)->(&(cCampoCodigo)))
        jLinha['descri']:= alltrim((cTabela)->(&(cCampoDescri)))

        aadd(xData,jLinha)

        (cTabela)->(dbSkip())

    Enddo
    
Return xData
